apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend112-app-frontend
  annotations:
    argocd/app-name: frontend112-app-frontend
    backstage.io/kubernetes-id: frontend112-app-frontend
    backstage.io/kubernetes-namespace: test
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: devhub-mad/frontend112-app-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - frontend
    - workshop
  links:
    - url: https://console-openshift-console.apps.cluster-wxd7f.wxd7f.sandbox1985.opentlc.com/dev-pipelines/ns/test/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.cluster-wxd7f.wxd7f.sandbox1985.opentlc.com/k8s/ns/test/deployments/frontend112-app-frontend
      title: Deployment
      icon: web
    - url: https://devspaces.apps.cluster-wxd7f.wxd7f.sandbox1985.opentlc.com/#https://github.com/devhub-mad/frontend112-app-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/varodrig"
  system: workshop-system-frontend112-app-frontend
  providesApis:
    - gateway-api-test
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-frontend112-app-frontend
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
spec:
  owner: "user:default/varodrig"

